services:
    app.pixel_tracking:
        class: AppBundle\Services\TrackingPixelService
        arguments:
            - "%tracking_pixels%"
            - '@templating'

    app.site_pages:
        class: AppBundle\Services\SitePagesService
        arguments:
            - '@router'
            - '@app.pixel_tracking'
            - "%site_pages%"

    ##################
    #   FORM TYPES   #
    ##################

    app.form.type.state:
        class: AppBundle\Form\Type\StateType
        arguments: ['%states%']
        tags: [{name: form.type }]

    #######################
    #   Twig Extensions   #
    #######################


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
