services:
    app.pixel_tracking:
        class: AppBundle\Services\TrackingPixelService
        arguments:
            - "@=parameter('tracking_pixels')"
            - '@templating'

    app.site_pages:
        class: AppBundle\Services\SitePagesService
        arguments:
            - '@router'
            - '@app.pixel_tracking'
            - "@=parameter('traffic_funnel')"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
