imports:
    - { resource: order_processors.yml }
    - { resource: tracking_pixels.yml}
    - { resource: products.yml }
    - { resource: site_text.yml }
    - { resource: site_pages.yml }
    - { resource: version_overrides.yml }
    - { resource: site_forms.yml }

# settings:
#   Application configuration settings.

parameters:
    site_config:
        settings:
           site_versions: ['default', 'v2']
