# order_processors:
#   Configuration values for CRM and merchant gateway apis. These integrations are used to process
#   transactions and provide order details.
parameters:
    site_config:
        order_processors:
            limelight:
                enabled: true
                testmode: true
                campaign_id: 'OFFERCAMPAGINID'
                api.key: 'APIKEYHERE'
                api.secret: 'APISECRETHERE'
                api.url: 'http://processhere.com'
