# pixel_tracking:
#   Paramaters used for traffic tracking systems and pixels. Pixels are defined by a name
#   and the definition of the variables expected. Twig templates are included from
#   app/Resources/pixel_tracking and named with a provider_name.pixel_name.html.twig
#   convention.
#
# Example configuration Entry:
#   cake:                                                   # Provider Name
#       conversion_pixel:                                   # Pixel Name
#           template: 'cake.conversion_pixel.html.twig'     # Template file in app/Resources/pixel_tracking/
#           variables:                                      # Colloction of variables
#               variable_name:                              # Name of variable
#                   options: {}                             # Options allowed
#                   required: true | false                  # A value is requried for pixel to render?
#                   default: 'default value'                # Default value

parameters:
    pixel_tracking:
        google:
            analytics:
                template: google.analytics.html.twig
                variables:
                    uid: {default: 'UA-MISSINGME', required: true}
                    utm_source: {}
                    utm_campaign: {}
                    utm_keyword: {}
            tag_manager:
                templates: google.tag_manager.html.twig
                variables:
                    account_id: {default: 'TagManagerId', required: true}
        cake:
            primary:
                template: cake.primary.html.twig
                variables:
                    campaign_id: {default: '123455', required: true}
                    action_event:
                        default: 'page_view'
                        options:
                            - 'lead_partial'
                            - 'lead_phone'
                            - 'lead_full'
                            - 'sell_primary'
                            - 'sell_up1'
                            - 'sell_up2'
                            - 'sell_up3'
                            - 'sell_down1'
                            - 'sell_down2'
                            - 'ell_save3'
                            - 'thank_you_page'
                            - 'page_view'

            convenversion_main:
                template: cake.conversion.html.twig

            convenversion_up1:
                template: cake.conversion.html.twig

            convenversion_up2:
                template: cake.conversion.html.twig
