parameters:
    site_config:
        products:
            product1:
                name: Test product
                one_click: false
            product2:
                name: Nature Clense
                Price: 19.47
                one_click: true
