imports:
    - { resource: order_processors.yml }
    - { resource: pixel_tracking.yml}
    - { resource: products.yml }
    - { resource: site_text.yml }
    - { resource: site_pages.yml }
    - { resource: version_overrides.yml }

# settings:
#   Application configuration settings.

parameters:
    site_config:
        settings:
           site_versions:
               default: { entry_url: ''}
               v2: { entry_url: 'get-it-now'}
