# site_pages
#    Configuration values that determin the path traffic takes through the site. Here we configure
#    the pages available in the funnel. The first page in the collection will be the first page
#    page loaded on the site. Pages are identified by their route names. Any nested variables will
#    be available to the page.
#
#    page config options:
#
#      page_tab_title
#           Title to show in the browser's tab
#
#      page_template
#           Template to file to render the page with. Templates live in app/Resources/views/default
#
#      page_route
#           Your pages url after .com, starting with the "/". i.e. /home or /checkout
#
#      page_handler
#           Specify the handler of this page. Options are "DisplayPage", "ProcessOrder", "SubmitLead", "SetSiteVersion"
#
#      forward_page
#           The name of the route a user is sent to when moving forward. This would also be used as
#           the form action post url when a user fills out a form.
#
#      exit_page
#           The name of a route the user should be sent to if they bounce.
#
#      page_forms
#           An Array of forms to be made available for display on the page
#
#      page_pixels
#           Pixels to be displayed on the page. Configure with a provier.pixel_name scalar
#           mapped to a sequence of variables and their values.
#
#      version_overrides
#           Apply page overide to configuration based on version
parameters:
    site_pages:
        entry_page:
            page_route: "/"
            forward_page: "pitch_page"
            new_version: "default"
            page_handler: "SetVersion"

        squeeze_page:
            page_tab_title: 'Welcome Page'
            page_route: '/welcome'
            page_handler: 'DisplayPage'
            page_template: 'squeeze.html.twig'
            forward_page: pitch_main
            exit_page: early_exit
            #page_forms: ['partial_lead']
            page_pixels:
                cake.primary: { campaign_id: 123, action_event: 'page-view'}
                google.analytics: { }
            #version_overrides:
            #    v2: 'squeeze_page_b'

        pitch_page:
            page_tab_title: 'Welcom'
            page_route: '/home'
            page_handler: 'DisplayPage'
            page_template: 'squeeze.html.twig'
            forward_page: pitch_main
            exit_page: early_exit
            #page_forms: ['partial_lead']
            page_pixels:
                cake.primary: { campaign_id: 123, action_event: 'page-view'}
                google.analytics: { }
            #version_overrides:
            #    v2: 'squeeze_page_b'

        checkout_page:
            page_route: '/checkout'
            page_handler: 'DisplayPage'
            page_tab_title: 'Welcom Page'
            page_template: 'squeeze.html.twig'
            forward_page: upsell_one
            exit_page: downsale_one
            page_forms: ['payment']
            page_pixels:
                cake.primary: { campaign_id: 123, action_event: 'page-view'}
                google.analytics: { }

