services:
    app.pixel_tracking:
        class: AppBundle\Services\TrackingPixelService
        arguments:
            - "%tracking_pixels%"
            - '@templating'

    app.site_pages:
        class: AppBundle\Services\SitePagesService
        arguments:
            - '@router'
            - '@app.pixel_tracking'
            - "%site_pages%"
            - '@templating'
            - '@app.form_builder'

    app.storage:
        class: AppBundle\Services\SessionStorageService
        arguments: ['@request_stack']

    app.form_builder:
        class: AppBundle\Services\FormBuilderService
        arguments: ['%site_forms%', '@request_stack']

    ##########################
    #   SYMFONY EXTENSIONS   #
    ##########################

    app.routing_loader:
        class: AppBundle\Routing\SitePagesLoader
        arguments: ['%site_pages%']
        tags: [{name: routing.loader}]
    app.site_pages_listner:
        class: AppBundle\EventListener\SitePagesListener
        arguments: ['%site_pages%', '@app.site_pages']
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    ##################
    #   FORM TYPES   #
    ##################

    app.form.type.state:
        class: AppBundle\Form\Type\StateType
        arguments: ['%states%']
        tags: [{name: form.type }]

    app.form.type.card_expiration_month:
        class: AppBundle\Form\Type\CardExpirationMonthType
        tags: [{name: form.type}]

    app.form.type.card_expiration_year:
        class: AppBundle\Form\Type\CardExpirationYear
        tags: [{name: form.type}]

    app.form.type.address:
        class: AppBundle\Form\AddressType
        tags: [{name: form.type}]

    app.form.type.billing_address:
        class: AppBundle\Form\BillingAddressType
        tags: [{name: form.type}]

